"""Run once: python seed.py  (from the backend/ directory)"""
import sqlite3, json

DB = "app.db"

SCHEMA = """
PRAGMA journal_mode=WAL;
CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    phone TEXT UNIQUE NOT NULL,
    role TEXT DEFAULT 'buyer',
    name TEXT DEFAULT '',
    location_lat REAL DEFAULT 0.0,
    location_lng REAL DEFAULT 0.0,
    subscription_status TEXT DEFAULT 'free',
    created_at TEXT DEFAULT (datetime('now'))
);
CREATE TABLE IF NOT EXISTS listings (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    seller_id INTEGER NOT NULL,
    title TEXT NOT NULL,
    description TEXT DEFAULT '',
    category TEXT NOT NULL,
    price REAL NOT NULL,
    unit TEXT NOT NULL DEFAULT 'kg',
    quantity REAL DEFAULT 0.0,
    location_lat REAL DEFAULT 0.0,
    location_lng REAL DEFAULT 0.0,
    location_name TEXT DEFAULT '',
    media_urls_json TEXT DEFAULT '[]',
    status TEXT DEFAULT 'active',
    created_at TEXT DEFAULT (datetime('now')),
    FOREIGN KEY (seller_id) REFERENCES users(id)
);
CREATE TABLE IF NOT EXISTS events (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    listing_id INTEGER NOT NULL,
    event_type TEXT NOT NULL,
    created_at TEXT DEFAULT (datetime('now')),
    FOREIGN KEY (listing_id) REFERENCES listings(id)
);
CREATE INDEX IF NOT EXISTS idx_users_phone ON users(phone);
CREATE INDEX IF NOT EXISTS idx_listings_seller ON listings(seller_id, created_at);
CREATE INDEX IF NOT EXISTS idx_listings_cat ON listings(category, status, created_at);
CREATE INDEX IF NOT EXISTS idx_events_listing ON events(listing_id, created_at);
"""

def img(keywords, lock):
    return f"https://loremflickr.com/800/600/{keywords}?lock={lock}"

# (title, category, price, unit, quantity, location, description, img_url)
PRODUCTS = [
    # ── AGRICULTURE (35) ──────────────────────────────────────────────────
    ("Fresh Red Tomatoes", "agriculture", 38, "kg", 800,
     "Koyambedu Market, Chennai",
     "Farm-fresh Grade A tomatoes from Thiruvallur district. Rich red colour, firm texture. Ideal for hotels, restaurants and retailers. Available daily. Minimum order: 50 kg.",
     img("tomatoes,red,vegetables", 1)),
    ("Red Onions – Nashik Variety", "agriculture", 26, "kg", 3000,
     "Koyambedu Market, Chennai",
     "Premium Nashik red onions with 45-day shelf life. Export-quality sorting. Supplied to supermarkets and vegetable chains. Minimum 100 kg per order.",
     img("onion,red,vegetables", 2)),
    ("Potatoes (Grade A)", "agriculture", 22, "kg", 2000,
     "Koyambedu Market, Chennai",
     "Washed and sorted potatoes. Two varieties available: Jyoti and Kufri Chipsona. Suitable for chips manufacturing, hotels and bulk buyers.",
     img("potatoes,vegetables,farm", 3)),
    ("Basmati Rice (1121)", "agriculture", 85, "kg", 5000,
     "Amritsar, Punjab",
     "Long-grain Basmati 1121 directly from mill. Aged 12 months for perfect aroma. Available in 25 kg and 50 kg bags. Export-quality lot.",
     img("rice,basmati,grain", 4)),
    ("Wheat (Sharbati)", "agriculture", 28, "kg", 10000,
     "Bhopal, Madhya Pradesh",
     "Premium Sharbati wheat with 12% protein content. Directly from farmers. Suitable for atta mills and bakeries. Moisture below 12%.",
     img("wheat,field,grain", 5)),
    ("Fresh Coconuts (Tamil Nadu)", "agriculture", 18, "piece", 5000,
     "Pollachi, Tamil Nadu",
     "Medium and large coconuts from Pollachi belt. Water coconuts and copra grade available. Direct from farm. Available year-round.",
     img("coconut,tropical,fruit", 6)),
    ("Alphonso Mangoes (Ratnagiri)", "agriculture", 280, "dozen", 200,
     "Ratnagiri, Maharashtra",
     "GI-tagged Ratnagiri Alphonso. Naturally ripened, no carbide used. Premium packing available. Pre-booking open. Season: March–June.",
     img("mango,tropical,yellow", 7)),
    ("Robusta Bananas", "agriculture", 22, "dozen", 1000,
     "Trichy, Tamil Nadu",
     "Raw and ripe robusta bananas from Theni farms. Uniform size, no blemish. Supplied to hotels, canteens and retail chains across Tamil Nadu.",
     img("banana,tropical,yellow", 8)),
    ("Baby Spinach (Fresh)", "agriculture", 45, "kg", 300,
     "Coimbatore, Tamil Nadu",
     "Tender baby spinach harvested daily. Rich in iron and minerals. Vacuum-packed option available. Supplied to restaurants and health food stores.",
     img("spinach,leaves,green", 9)),
    ("Cauliflower (Ooty)", "agriculture", 35, "kg", 500,
     "Ooty, Tamil Nadu",
     "White, compact cauliflower from Nilgiri hills. Pesticide residue tested. Supplied to supermarkets. Available October to February.",
     img("cauliflower,white,vegetable", 10)),
    ("Red Capsicum & Bell Pepper", "agriculture", 90, "kg", 400,
     "Kodaikanal, Tamil Nadu",
     "Mixed bell peppers – red, yellow, green. Grown at 2000m altitude. Crunchy texture, long shelf life. Minimum order 20 kg.",
     img("capsicum,pepper,red", 11)),
    ("Guntur Green Chillies", "agriculture", 55, "kg", 600,
     "Guntur, Andhra Pradesh",
     "Fresh and dried Guntur sannam chillies. High capsaicin content. Supply available throughout the year. Major hotel chains served.",
     img("chili,green,pepper", 12)),
    ("Tender Coconut Water", "agriculture", 25, "piece", 2000,
     "Ernakulam, Kerala",
     "Young green coconuts for drinking. Sweet water, tender flesh. Supplied to juice bars, events and resorts. Bulk pricing available.",
     img("coconut,green,tropical", 13)),
    ("Fresh Ginger (Wayanad)", "agriculture", 95, "kg", 1000,
     "Wayanad, Kerala",
     "Mature ginger with high essential oil content. Dry and wet varieties. GI indication area. Supplied to spice processors and exporters.",
     img("ginger,root,spice", 14)),
    ("Garlic (Ooty Hill Garlic)", "agriculture", 120, "kg", 500,
     "Ooty, Tamil Nadu",
     "Small-clove hill garlic with intense flavour. Organically grown without chemical fertilisers. Supplied to ayurvedic companies and restaurants.",
     img("garlic,white,spice", 15)),
    ("Sweet Corn (Fresh)", "agriculture", 15, "piece", 2000,
     "Coimbatore, Tamil Nadu",
     "Yellow sweet corn, freshly harvested. Suitable for roasting, grilling and processing. Available June–September.",
     img("corn,maize,yellow", 16)),
    ("Watermelon (Kiran)", "agriculture", 12, "kg", 5000,
     "Dindigul, Tamil Nadu",
     "Kiran variety watermelons, 6–8 kg average weight. Deep red flesh, high sugar content. Farm-direct supply to retailers and juice shops.",
     img("watermelon,fruit,summer", 17)),
    ("Fresh Turmeric (Raw)", "agriculture", 48, "kg", 800,
     "Erode, Tamil Nadu",
     "Raw turmeric from Erode, Asia's largest turmeric market. High curcumin content (6%+). Supplied to ayurvedic and cosmetic manufacturers.",
     img("turmeric,root,yellow", 18)),
    ("Pomegranate (Bhagwa)", "agriculture", 110, "kg", 600,
     "Dharmapuri, Tamil Nadu",
     "Bhagwa variety pomegranate with deep red arils. Sugar content 16–18 Brix. Supplied to juice factories and premium retail chains.",
     img("pomegranate,fruit,red", 19)),
    ("Grapes (Thomson Seedless)", "agriculture", 75, "kg", 1200,
     "Theni, Tamil Nadu",
     "Green seedless grapes from Theni vineyards. Crunchiness maintained with cold-chain logistics. Export-quality, residue-free.",
     img("grapes,vineyard,fruit", 20)),
    ("Ooty Strawberries", "agriculture", 200, "kg", 150,
     "Ooty, Tamil Nadu",
     "Fresh strawberries grown at 2200m altitude. Available November–February. Supplied to hotels, bakeries and ice cream manufacturers.",
     img("strawberry,red,fruit", 21)),
    ("Jasmine Flowers (Madurai Malli)", "agriculture", 350, "kg", 100,
     "Madurai, Tamil Nadu",
     "Madurai Malli – GI-tagged jasmine. Freshly harvested at 4 am. Supplied to temples, event companies and perfume manufacturers daily.",
     img("jasmine,flower,white", 22)),
    ("Drumstick (Moringa)", "agriculture", 40, "kg", 400,
     "Salem, Tamil Nadu",
     "Fresh drumstick from PKM-1 variety trees. Rich in vitamins. Supplied to hotels and hospitals. Available year-round from irrigated farms.",
     img("moringa,green,vegetable", 23)),
    ("Raw Papaya", "agriculture", 18, "kg", 600,
     "Villupuram, Tamil Nadu",
     "Raw papaya for cooking and making papain. Red Lady variety available. Supplied to pickle manufacturers and canteen kitchens.",
     img("papaya,tropical,fruit", 24)),
    ("Guava (Allahabad Safeda)", "agriculture", 45, "kg", 500,
     "Krishnagiri, Tamil Nadu",
     "White-flesh guava with high vitamin C. Firm texture, long shelf life. Supplied to juice manufacturers and supermarkets.",
     img("guava,fruit,tropical", 25)),
    ("Bitter Gourd", "agriculture", 38, "kg", 300,
     "Coimbatore, Tamil Nadu",
     "Fresh bitter gourd sourced from contract farmers. Available in long and short varieties. Supplied to vegetable traders and hospitals.",
     img("bittergourd,vegetable,green", 26)),
    ("Lady's Finger (Okra)", "agriculture", 42, "kg", 350,
     "Trichy, Tamil Nadu",
     "Tender okra harvested at 3–4 inches. Free of blemishes and spots. Supplied to hotels and vegetable markets. Available year-round.",
     img("okra,vegetable,green", 27)),
    ("Groundnuts (Bold)", "agriculture", 68, "kg", 2000,
     "Tirunelveli, Tamil Nadu",
     "Bold groundnut from Tirunelveli belt. 6/8 and 8/9 count. Oil content 48–52%. Supplied to oil mills, snack manufacturers and exporters.",
     img("peanuts,groundnut,legume", 28)),
    ("Curry Leaves (Fresh)", "agriculture", 80, "kg", 100,
     "Madurai, Tamil Nadu",
     "Fresh curry leaves harvested daily. Rich aroma. Supplied to restaurants, hotels and masala manufacturers across South India.",
     img("curry,leaves,herbs", 29)),
    ("Sesame Seeds (White)", "agriculture", 145, "kg", 1500,
     "Tirupur, Tamil Nadu",
     "White sesame, 99.99% purity grade. Natural and hulled varieties available. Supplied to oil mills, bakeries and exporters.",
     img("sesame,seeds,white", 30)),
    ("Coriander (Fresh Bunch)", "agriculture", 30, "kg", 200,
     "Chennai, Tamil Nadu",
     "Fresh coriander leaves, harvested at dawn. Roots attached for longer freshness. Supplied to hotels, canteens and vegetable markets daily.",
     img("coriander,herbs,green", 31)),
    ("Brinjal (Purple Long)", "agriculture", 28, "kg", 400,
     "Tirunelveli, Tamil Nadu",
     "Long purple brinjal from Tirunelveli farms. Tender and flavourful. Supplied to hotels and vegetable traders. Available throughout the year.",
     img("eggplant,purple,vegetable", 32)),
    ("Raw Tamarind (Pulp)", "agriculture", 52, "kg", 2000,
     "Vellore, Tamil Nadu",
     "Seedless tamarind pulp from Vellore. Sourness index tested. Supplied to food processors, hotels and pickle manufacturers.",
     img("tamarind,pod,brown", 33)),
    ("Black Pepper (Malabar)", "agriculture", 580, "kg", 500,
     "Kozhikode, Kerala",
     "Malabar black pepper, bold grade. Piperine content above 5%. GI-tagged produce. Supplied to spice exporters and masala companies.",
     img("pepper,black,spice", 34)),
    ("Red Chilli Powder (Bulk)", "agriculture", 145, "kg", 1000,
     "Guntur, Andhra Pradesh",
     "S4 grade Guntur red chilli powder. ASTA colour value 120+. Supplied in 25 kg PP bags to food processors and masala manufacturers.",
     img("chili,powder,red", 35)),

    # ── LIVESTOCK & FOOD (25) ─────────────────────────────────────────────
    ("Broiler Chicken (Live)", "livestock", 115, "kg", 2000,
     "Namakkal, Tamil Nadu",
     "Farm-raised broiler chicken. Average weight 2–2.5 kg per bird. FSSAI-certified farm. Supplied live or dressed to hotels and meat shops.",
     img("chicken,poultry,farm", 36)),
    ("Country Chicken (Nattu Kozhi)", "livestock", 360, "kg", 500,
     "Erode, Tamil Nadu",
     "Free-range country chicken. Raised on natural feed – no antibiotics. Superior taste and nutrition. Supplied to premium restaurants.",
     img("chicken,freerange,poultry", 37)),
    ("Duck Eggs (Fresh)", "livestock", 12, "piece", 5000,
     "Kanyakumari, Tamil Nadu",
     "Large duck eggs from free-range ducks. Rich in protein. Supplied in trays of 30. Available daily. Bulk orders preferred.",
     img("eggs,duck,poultry", 38)),
    ("Buffalo Milk (Fresh)", "livestock", 55, "litre", 1000,
     "Vellore, Tamil Nadu",
     "Fresh buffalo milk with 6–7% fat. Supplied daily to dairies, paneer manufacturers and sweet shops. Hygienically collected and chilled.",
     img("milk,buffalo,dairy", 39)),
    ("Homemade Paneer", "livestock", 320, "kg", 200,
     "Coimbatore, Tamil Nadu",
     "Fresh paneer made from full-fat milk. Soft texture, low moisture. Supplied to restaurants, caterers and sweet shops. Made fresh daily.",
     img("paneer,cheese,dairy", 40)),
    ("Vanjaram Fish (Seer)", "livestock", 750, "kg", 100,
     "Rameswaram, Tamil Nadu",
     "Fresh-caught seer fish (king fish) from Gulf of Mannar. Iced and transported within 6 hours of catch. Supplied to hotels and fish markets.",
     img("fish,seafood,ocean", 41)),
    ("Tiger Prawns (Fresh)", "livestock", 950, "kg", 80,
     "Nagapattinam, Tamil Nadu",
     "Live-caught tiger prawns from Bay of Bengal. Size: 21/25 count. Supplied to star hotels, export processing units and seafood restaurants.",
     img("prawns,shrimp,seafood", 42)),
    ("Rohu Fish (Fresh)", "livestock", 220, "kg", 300,
     "Alappuzha, Kerala",
     "Fresh water rohu, farm-raised. Average 1–2 kg size. Supplied to fish markets and hotels. Available daily from integrated fish farm.",
     img("fish,freshwater,silver", 43)),
    ("Fresh Mutton (Goat)", "livestock", 680, "kg", 200,
     "Salem, Tamil Nadu",
     "Fresh goat mutton. FSSAI-approved slaughterhouse. Biryani and curry cuts available. Supplied to hotels and meat shops daily.",
     img("goat,meat,mutton", 44)),
    ("Honey (Pure Forest)", "livestock", 850, "kg", 200,
     "Valparai, Tamil Nadu",
     "Raw forest honey from Anamalai hills. Unprocessed, unheated. Multiple floral varieties available. Supplied to health stores and Ayurvedic companies.",
     img("honey,golden,natural", 45)),
    ("A2 Cow Milk (Gir)", "livestock", 90, "litre", 300,
     "Madurai, Tamil Nadu",
     "Pure A2 milk from indigenous Gir cows. Fed on natural grass and jaggery. Supplied to health-conscious individuals and premium dairy brands.",
     img("milk,cow,dairy", 46)),
    ("Dried Sardines (Nethili)", "livestock", 250, "kg", 500,
     "Rameswaram, Tamil Nadu",
     "Sun-dried sardines from traditional fishermen. Rich in omega-3. Supplied to hotels, distributors and export units across South India.",
     img("fish,dried,sardine", 47)),
    ("Catfish (Keluthi – Fresh)", "livestock", 280, "kg", 150,
     "Thanjavur, Tamil Nadu",
     "Farm-raised catfish. Live delivery within 50 km. Excellent for curries. Supplied to restaurants and fish markets.",
     img("catfish,fish,freshwater", 48)),
    ("Fresh Crab (Sea)", "livestock", 620, "kg", 60,
     "Thoothukudi, Tamil Nadu",
     "Live sea crab from Gulf of Mannar. Green mud crab and rock crab available. Supplied to seafood restaurants and export units.",
     img("crab,seafood,ocean", 49)),
    ("Quail Eggs (Fresh)", "livestock", 4, "piece", 10000,
     "Namakkal, Tamil Nadu",
     "Fresh quail eggs from organised quail farm. Rich in vitamins B1 and B2. Supplied to hospitals, hotels and health food companies.",
     img("eggs,quail,speckled", 50)),
    ("Goat Milk (Raw)", "livestock", 120, "litre", 100,
     "Tirupur, Tamil Nadu",
     "Raw goat milk, naturally homogenised. Lower lactose than cow milk. Ideal for cheese making. Supplied to artisan dairies.",
     img("milk,goat,dairy", 51)),
    ("Squid (Fresh)", "livestock", 520, "kg", 80,
     "Tuticorin, Tamil Nadu",
     "Fresh squid cleaned and iced. Size 10/20 per kg. Supplied to Chinese restaurants, coastal hotels and export processing plants.",
     img("squid,seafood,calamari", 52)),
    ("Lobster (Spiny)", "livestock", 2200, "kg", 20,
     "Rameswaram, Tamil Nadu",
     "Live spiny lobster from Gulf of Mannar. Average 300–500 g each. Supplied to five-star hotels and seafood export companies.",
     img("lobster,seafood,ocean", 53)),
    ("Village Curd (Thayir)", "livestock", 55, "kg", 200,
     "Madurai, Tamil Nadu",
     "Traditional set curd made from full-fat buffalo milk. No preservatives. Supplied in clay pots or food-grade containers to restaurants.",
     img("curd,yogurt,dairy", 54)),
    ("Desi Ghee (Pure)", "livestock", 1200, "kg", 100,
     "Tiruvannamalai, Tamil Nadu",
     "Bilona ghee made from A2 cow milk using traditional wooden churner. Golden colour, rich aroma. Supplied to Ayurvedic brands and premium retailers.",
     img("ghee,butter,golden", 55)),
    ("Tilapia Fish (Farm)", "livestock", 185, "kg", 500,
     "Rajapalayam, Tamil Nadu",
     "Farm-raised tilapia. Antibiotic-free. Average 250–400 g each. Supplied to canteens, schools and fish markets. Available daily.",
     img("tilapia,fish,pond", 56)),
    ("Pork (Fresh – Country)", "livestock", 420, "kg", 150,
     "Nagercoil, Tamil Nadu",
     "Country pork, freshly slaughtered. Various cuts available. Supplied to pork specialty restaurants and meat shops in South Tamil Nadu.",
     img("pork,meat,fresh", 57)),
    ("Oysters (Fresh)", "livestock", 380, "kg", 40,
     "Mandapam, Tamil Nadu",
     "Fresh pearl oysters from Palk Bay. High zinc content. Supplied to premium seafood restaurants and coastal resorts.",
     img("oyster,shellfish,seafood", 58)),
    ("Turkey (Live)", "livestock", 450, "kg", 50,
     "Coimbatore, Tamil Nadu",
     "Live turkey birds, 4–6 kg each. Farm-raised on grain feed. High demand during festive season. Advance booking recommended.",
     img("turkey,poultry,farm", 59)),
    ("Rabbit Meat (Fresh)", "livestock", 580, "kg", 30,
     "Salem, Tamil Nadu",
     "Farm-raised rabbit, lean and healthy. Low cholesterol. Supplied to specialty restaurants and health food enthusiasts.",
     img("rabbit,meat,farm", 60)),

    # ── TEXTILE (25) ──────────────────────────────────────────────────────
    ("Cotton T-Shirts (Bulk – 100 pcs)", "textile", 75, "piece", 5000,
     "Tirupur, Tamil Nadu",
     "Round-neck cotton T-shirts, 180 GSM. Sizes S to XXL available. White and multicolour. Minimum 100 pcs per order. OEM printing available.",
     img("tshirt,cotton,fashion", 61)),
    ("Kanjivaram Silk Sarees", "textile", 4500, "piece", 200,
     "Kanchipuram, Tamil Nadu",
     "Authentic handwoven Kanjivaram silk sarees with GI tag. Pure zari border. Available in 50+ colour combinations. Bulk pricing for retailers.",
     img("saree,silk,colorful", 62)),
    ("Cotton Fabric (Premium)", "textile", 85, "metre", 10000,
     "Tirupur, Tamil Nadu",
     "40s combed cotton fabric, 58 inch width. Reactive-dyed, 100+ colours available. Suitable for shirting, dress material and garments.",
     img("fabric,cotton,textile", 63)),
    ("Denim Jeans (Bulk – 50 pcs)", "textile", 350, "piece", 2000,
     "Ahmedabad, Gujarat",
     "Stretch denim jeans, 11 oz fabric. Sizes 28–38 available. Five-pocket style. Ideal for retail stores and export buyers.",
     img("jeans,denim,fashion", 64)),
    ("Linen Fabric (Natural)", "textile", 220, "metre", 3000,
     "Kolkata, West Bengal",
     "Pure linen fabric, 60 inch width. Natural and dyed versions. 100% linen or linen-cotton blend. Supplied to garment exporters.",
     img("linen,fabric,natural", 65)),
    ("Polyester Fabric (4-way Stretch)", "textile", 65, "metre", 8000,
     "Surat, Gujarat",
     "4-way stretch polyester-spandex fabric. 150 GSM. Used for sportswear and leggings. Available in 200+ colours. MOQ: 500 metres.",
     img("polyester,fabric,colorful", 66)),
    ("Khadi Fabric (Handspun)", "textile", 180, "metre", 2000,
     "Coimbatore, Tamil Nadu",
     "Authentic khadi woven on charka looms. Cotton and silk varieties. KVIC certified. Supplied to boutiques, govt stores and fashion designers.",
     img("khadi,handwoven,fabric", 67)),
    ("School Uniforms (Bulk – 200 sets)", "textile", 320, "piece", 1000,
     "Tirupur, Tamil Nadu",
     "Ready-made school uniforms – shirt and trouser/skirt set. Custom colour and logo printing available. Supplied to schools and DSEs.",
     img("uniform,school,clothing", 68)),
    ("Bed Sheets (Hotel Grade)", "textile", 480, "piece", 2000,
     "Karur, Tamil Nadu",
     "230 TC percale bed sheets. Sizes: single, double, king. White and pastel colours. Supplied to hotels, hospitals and hostels.",
     img("bedsheet,linen,bedroom", 69)),
    ("Cotton Towels (Bulk)", "textile", 95, "piece", 5000,
     "Karur, Tamil Nadu",
     "400 GSM cotton towels. Sizes: hand, face and bath. White and coloured. Exported to Europe and Gulf. Bulk pricing from 500 pcs.",
     img("towel,cotton,white", 70)),
    ("Chiffon Fabric", "textile", 75, "metre", 5000,
     "Surat, Gujarat",
     "Lightweight chiffon fabric. 60 gsm. 44-inch width. Plain and printed designs. Used for sarees, dupattas and dress material.",
     img("chiffon,fabric,light", 71)),
    ("Non-Woven Shopping Bags", "textile", 8, "piece", 50000,
     "Tirupur, Tamil Nadu",
     "80 GSM non-woven polypropylene bags. Custom printing available. Eco-friendly alternative to plastic. Minimum order: 1000 pcs.",
     img("bags,shopping,reusable", 72)),
    ("Sports Jerseys (Sublimation)", "textile", 220, "piece", 1000,
     "Tirupur, Tamil Nadu",
     "Polyester sublimation jerseys for cricket, football and kabaddi. Full custom design. MOQ 10 pcs. Delivered in 7–10 days.",
     img("jersey,sports,colorful", 73)),
    ("Handloom Cotton Sarees", "textile", 850, "piece", 500,
     "Madurai, Tamil Nadu",
     "Traditional handloom sarees woven on pit looms. Pure cotton, natural dyes option. Supplied to govt emporiums and boutiques.",
     img("saree,handloom,cotton", 74)),
    ("Jute Bags (Eco-Friendly)", "textile", 55, "piece", 10000,
     "Kolkata, West Bengal",
     "6 oz natural jute bags with cotton lining option. Custom screen printing. Exported to Europe. Supplied to supermarkets and eco brands.",
     img("jute,bag,natural", 75)),
    ("Woolen Shawls (Pashmina Blend)", "textile", 650, "piece", 500,
     "Ludhiana, Punjab",
     "Pashmina-blend shawls, 70% wool, 30% pashmina. Soft and warm. Embroidered and plain designs. Bulk pricing for retail chains.",
     img("shawl,wool,warm", 76)),
    ("Block Print Fabric", "textile", 165, "metre", 1000,
     "Jaipur, Rajasthan",
     "Hand block-printed cotton fabric using natural dyes. Traditional Rajasthani patterns. Supplied to fashion designers and boutiques.",
     img("blockprint,fabric,pattern", 77)),
    ("Elastic Waistband Fabric", "textile", 42, "metre", 5000,
     "Tirupur, Tamil Nadu",
     "Warp-knit elastic fabric. 75% polyester, 25% spandex. Used for waistbands, lingerie and sportswear. Available in 2–6 inch widths.",
     img("elastic,fabric,stretch", 78)),
    ("Curtain Fabric (Blackout)", "textile", 135, "metre", 3000,
     "Karur, Tamil Nadu",
     "Triple-weave blackout fabric. 100% light blocking. 54-inch width. Supplied to hotels, hospitals and commercial interior companies.",
     img("curtain,fabric,interior", 79)),
    ("Hospital Uniforms (Scrubs)", "textile", 380, "piece", 2000,
     "Coimbatore, Tamil Nadu",
     "Medical scrubs with antimicrobial finish. Poly-cotton blend. Custom colour and logo printing. Supplied to hospitals and clinics.",
     img("scrubs,medical,uniform", 80)),
    ("Canvas Fabric (Heavy Duty)", "textile", 95, "metre", 3000,
     "Coimbatore, Tamil Nadu",
     "16 oz duck canvas fabric. Used for bags, tents and industrial covers. Natural and dyed versions. Flame-retardant treatment available.",
     img("canvas,fabric,heavy", 81)),
    ("Lycra Leggings Fabric", "textile", 58, "metre", 8000,
     "Tirupur, Tamil Nadu",
     "Nylon-lycra fabric, 200 GSM. Ultra-soft, four-way stretch. Used for yoga pants and activewear. 50+ colours available.",
     img("lycra,leggings,stretch", 82)),
    ("Table Cloth (Restaurant Grade)", "textile", 185, "piece", 1000,
     "Karur, Tamil Nadu",
     "Damask table cloths with stain-resistant finish. Sizes 60x60 to 60x120. White and coloured. Supplied to restaurants and event companies.",
     img("tablecloth,restaurant,linen", 83)),
    ("Embroidered Dupatta", "textile", 420, "piece", 500,
     "Lucknow, Uttar Pradesh",
     "Chikankari hand-embroidered dupattas on georgette. Traditional Lucknow craft. GI-tagged. Supplied to fashion boutiques and online retailers.",
     img("dupatta,embroidered,indian", 84)),
    ("Tie-Dye Fabric (Shibori)", "textile", 195, "metre", 2000,
     "Jaipur, Rajasthan",
     "Hand tie-dyed cotton fabric. Shibori and Bandhani patterns. Natural indigo and synthetic dye options. Supplied to fashion designers.",
     img("tiedye,fabric,colorful", 85)),

    # ── MANUFACTURING (15) ────────────────────────────────────────────────
    ("CPVC Hot Water Pipes (6m)", "manufacturing", 285, "piece", 5000,
     "Ahmedabad, Gujarat",
     "CPVC pipes suitable for hot and cold water supply. Sizes 1/2 inch to 2 inch. ISI-marked. Supplied to plumbing contractors and distributors.",
     img("pipe,plumbing,pvc", 86)),
    ("TMT Steel Bars (Fe550)", "manufacturing", 68000, "tonne", 200,
     "Raipur, Chhattisgarh",
     "Fe550 grade TMT steel bars. Sizes: 8mm to 32mm. IS:1786 certified. Supplied to construction companies and building material dealers.",
     img("steel,bar,construction", 87)),
    ("Ceramic Floor Tiles (24x24)", "manufacturing", 45, "piece", 50000,
     "Morbi, Gujarat",
     "Double-charged vitrified tiles, 24x24 inch. 7 mm thickness. 300+ designs. PEI-4 wear rating. Supplied to builders and tile shops.",
     img("tiles,ceramic,floor", 88)),
    ("PPC Cement (50kg bag)", "manufacturing", 420, "bag", 5000,
     "Chennai, Tamil Nadu",
     "Portland Pozzolana Cement. 43 grade. ISI-marked. Supplied in 50 kg PP bags. Bulk pricing for contractors. Delivery within 48 hours.",
     img("cement,bag,construction", 89)),
    ("LED Bulbs (Bulk – 100 pcs)", "manufacturing", 65, "piece", 10000,
     "Noida, Uttar Pradesh",
     "9W LED bulb, E27 base. Warm white 3000K and cool white 6500K. BEE 5-star rated. 25,000-hour lifespan. OEM available.",
     img("led,bulb,light", 90)),
    ("HDPE Water Storage Tanks", "manufacturing", 5800, "piece", 500,
     "Chennai, Tamil Nadu",
     "Food-grade HDPE water tanks. Capacity: 500L to 10,000L. ISI-marked. UV-stabilised. Triple-layer insulation available.",
     img("tank,water,storage", 91)),
    ("Aluminium Sections & Profiles", "manufacturing", 215, "kg", 10000,
     "Bengaluru, Karnataka",
     "Extruded aluminium profiles. T-slot, rectangular and L-angle available. Anodised and powder-coated finish. Supplied to fabricators.",
     img("aluminium,profile,metal", 92)),
    ("Safety Helmets (ISI marked)", "manufacturing", 185, "piece", 5000,
     "Coimbatore, Tamil Nadu",
     "HDPE safety helmets with 6-point suspension. IS:2925 certified. Ratchet and pinlock models. Custom printing available.",
     img("helmet,safety,construction", 93)),
    ("Wooden Planks (Teak)", "manufacturing", 1800, "piece", 1000,
     "Coimbatore, Tamil Nadu",
     "Seasoned teak wood planks, 12–18mm thickness. Kiln-dried to 12% moisture. Supplied to furniture manufacturers and construction companies.",
     img("wood,plank,teak", 94)),
    ("Commercial Plywood (BWP)", "manufacturing", 3200, "piece", 2000,
     "Yamunanagar, Haryana",
     "18mm BWP-grade commercial plywood. IS:303 certified. Face: gurjan, core: poplar. Boiling waterproof. Supplied to interior contractors.",
     img("plywood,wood,panel", 95)),
    ("Rubber Conveyor Belt", "manufacturing", 850, "metre", 500,
     "Ahmedabad, Gujarat",
     "Multi-ply rubber conveyor belt. EP150 to EP630 grade. Widths 300mm to 1200mm. Supplied to mining, quarry and logistics companies.",
     img("conveyor,belt,industrial", 96)),
    ("Industrial Safety Gloves", "manufacturing", 45, "pair", 20000,
     "Kanpur, Uttar Pradesh",
     "Cut-resistant nitrile-coated gloves. EN388 certified. Sizes S-XL. Supplied to manufacturing plants, chemical factories and logistics companies.",
     img("gloves,safety,industrial", 97)),
    ("Fire Bricks (High Temp)", "manufacturing", 28, "piece", 10000,
     "Hyderabad, Telangana",
     "High-alumina fire bricks for furnace lining. Temperature resistance up to 1500 degrees C. Supplied to steel plants, glass factories and kilns.",
     img("brick,fire,industrial", 98)),
    ("Galvanised Iron Wire (18 gauge)", "manufacturing", 75, "kg", 5000,
     "Ludhiana, Punjab",
     "GI binding wire, 18 and 20 gauge. Hot-dip galvanised. Tensile strength 350-450 MPa. Supplied in 5 kg and 25 kg coils.",
     img("wire,iron,coil", 99)),
    ("Paint (Industrial Epoxy – 20L)", "manufacturing", 2850, "can", 500,
     "Mumbai, Maharashtra",
     "2-component epoxy floor paint. High gloss, chemical-resistant. Coverage: 10-12 sqm/litre. Supplied to factories and warehouses.",
     img("paint,epoxy,industrial", 100)),

    # ── FOOD & SPICES (12) ────────────────────────────────────────────────
    ("Turmeric Powder (Erode Gold)", "spices", 185, "kg", 2000,
     "Erode, Tamil Nadu",
     "Premium Erode turmeric powder. Curcumin content above 5%. Bright yellow colour. FSSAI-certified. Supplied in 25 kg PP bags to spice brands and exporters.",
     img("turmeric,powder,yellow", 101)),
    ("Cumin Seeds (Jeera – Rajasthani)", "spices", 320, "kg", 1500,
     "Unjha, Gujarat",
     "Bold Rajasthani cumin seeds. High volatile oil content. Cleaned and graded. Supplied to masala manufacturers, hotels and exporters.",
     img("cumin,seeds,spice", 102)),
    ("Green Cardamom (Alleppey)", "spices", 2800, "kg", 200,
     "Idukki, Kerala",
     "Premium 8mm+ green cardamom from Idukki hills. Bold pods, high oil content. GI-tagged. Supplied to sweet manufacturers and masala companies.",
     img("cardamom,green,spice", 103)),
    ("Cinnamon Sticks (Ceylon)", "spices", 850, "kg", 500,
     "Coimbatore, Tamil Nadu",
     "True Ceylon cinnamon sticks. 6-inch and 3-inch cuts. Mild and sweet flavour. Supplied to bakeries, beverage companies and exporters.",
     img("cinnamon,sticks,spice", 104)),
    ("Cloves (Whole – Zanzibar)", "spices", 1200, "kg", 300,
     "Chennai, Tamil Nadu",
     "Premium whole cloves. High eugenol content (16%+). Hand-picked and sun-dried. Supplied to masala manufacturers and pharmaceutical companies.",
     img("cloves,spice,aromatic", 105)),
    ("Sambar Powder (Restaurant Grade)", "spices", 220, "kg", 1000,
     "Madurai, Tamil Nadu",
     "Traditional sambar powder blend. Made from sun-dried coriander, red chilli, cumin and dals. No artificial colour. Supplied to restaurants and canteens.",
     img("spice,powder,blend", 106)),
    ("Biryani Masala (Special Blend)", "spices", 380, "kg", 800,
     "Hyderabad, Telangana",
     "Authentic Hyderabadi biryani masala. Whole spice blend with saffron base. No preservatives. Supplied to restaurant chains and hotel kitchens.",
     img("biryani,masala,spice", 107)),
    ("Cold-Pressed Coconut Oil", "spices", 280, "litre", 2000,
     "Pollachi, Tamil Nadu",
     "Virgin cold-pressed coconut oil. Extracted from fresh coconuts at 40 degrees. No heat treatment. Rich in MCTs. Supplied to health stores and FMCG brands.",
     img("coconut,oil,natural", 108)),
    ("Palm Jaggery (Karupatti)", "spices", 160, "kg", 1500,
     "Tirunelveli, Tamil Nadu",
     "Traditional palm sugar jaggery (karupatti). Rich mineral content. Natural sweetener. No chemicals. Supplied to Ayurvedic brands and natural food stores.",
     img("jaggery,palm,brown", 109)),
    ("Mustard Seeds (Black & Yellow)", "spices", 90, "kg", 3000,
     "Rajkot, Gujarat",
     "Black and yellow mustard seeds. Free from impurities. Used in cooking and oil extraction. Supplied to oil mills and spice manufacturers.",
     img("mustard,seeds,yellow", 110)),
    ("Groundnut Oil (Filtered)", "spices", 180, "litre", 5000,
     "Tirunelveli, Tamil Nadu",
     "Traditional filter-pressed groundnut oil. Rich nutty aroma. Wood-pressed option available. Supplied to retailers and food manufacturers.",
     img("groundnut,oil,cooking", 111)),
    ("Star Anise (Whole)", "spices", 680, "kg", 400,
     "Chennai, Tamil Nadu",
     "Whole star anise, strong aroma. High essential oil content. Used in masalas, biryani and herbal teas. Supplied to spice distributors and exporters.",
     img("staranise,spice,herb", 112)),

    # ── CONSTRUCTION (12) ─────────────────────────────────────────────────
    ("AAC Lightweight Blocks (8 inch)", "construction", 42, "piece", 50000,
     "Chennai, Tamil Nadu",
     "Autoclaved Aerated Concrete blocks. 8x4x2.5 inch size. Lightweight, thermal insulating. BIS-certified. Supplied to builders and construction contractors.",
     img("aac,block,construction", 116)),
    ("M-Sand (River Grade)", "construction", 850, "tonne", 500,
     "Salem, Tamil Nadu",
     "Manufactured sand for concrete and plaster. TNPCB-approved. Free from silt and organic matter. Bulk supply to construction sites in Tamil Nadu.",
     img("sand,construction,building", 117)),
    ("Black Galaxy Granite Slabs", "construction", 280, "piece", 2000,
     "Krishnagiri, Tamil Nadu",
     "Premium black galaxy granite slabs, 18mm thickness. Polished finish. Quarried from Krishnagiri. Supplied to interior contractors and fabricators.",
     img("granite,black,stone", 118)),
    ("Roofing Sheets (Galvalume Steel)", "construction", 380, "piece", 5000,
     "Coimbatore, Tamil Nadu",
     "Galvalume steel roofing sheets. 0.5mm thickness. 20 ft and 12 ft lengths. Corrugated and trapezoidal profiles. ISI-marked.",
     img("roofing,sheet,metal", 119)),
    ("Tempered Glass Panels (8mm)", "construction", 185, "piece", 1000,
     "Chennai, Tamil Nadu",
     "8mm clear tempered safety glass. Sizes up to 8x4 feet. IS:2553 certified. Used for partitions, balconies and facades.",
     img("glass,panel,transparent", 120)),
    ("20mm Stone Aggregate (Crushed)", "construction", 650, "tonne", 1000,
     "Dharmapuri, Tamil Nadu",
     "Crushed granite aggregate, 20mm size. Cubical shape, low flakiness. Used for concrete work, road base and RCC. Bulk delivery available.",
     img("stone,aggregate,gravel", 121)),
    ("Hollow Concrete Blocks (6 inch)", "construction", 28, "piece", 100000,
     "Coimbatore, Tamil Nadu",
     "6-inch hollow concrete blocks. Compressive strength 7.5 MPa. IS:2185 certified. Used for load-bearing and partition walls.",
     img("concrete,block,hollow", 122)),
    ("Gypsum Ceiling Boards (4x8 ft)", "construction", 420, "piece", 5000,
     "Chennai, Tamil Nadu",
     "12mm gypsum boards for false ceilings and partition walls. Moisture-resistant and fire-resistant grades. Supplied with accessories.",
     img("gypsum,board,ceiling", 123)),
    ("Teak Wood Door Frames", "construction", 3500, "piece", 500,
     "Coimbatore, Tamil Nadu",
     "Seasoned teak wood door frames. 3x7 ft standard size. Kiln-dried. Custom sizes available. Supplied to builders and interior contractors.",
     img("door,frame,wood", 124)),
    ("WPC Door Panels (Waterproof)", "construction", 4800, "piece", 300,
     "Chennai, Tamil Nadu",
     "Wood-plastic composite doors. 30mm thickness. 100% waterproof. Termite-proof. Available in 10+ textures. Supplied to residential builders.",
     img("door,panel,composite", 125)),
    ("Steel Angles (L-Section 50x50)", "construction", 62000, "tonne", 100,
     "Chennai, Tamil Nadu",
     "Mild steel angles, 50x50x5mm. IS:2062 Grade E250. Used for fabrication, shelving and structural work. Supplied in 6-metre lengths.",
     img("steel,angle,metal", 126)),
    ("PVC Window Frames (5 chamber)", "construction", 1850, "piece", 1000,
     "Ahmedabad, Gujarat",
     "5-chamber PVC uPVC window frames. White and woodgrain finish. Double-sealed. Thermal break design. Supplied to builders and glazing contractors.",
     img("window,pvc,frame", 127)),

    # ── ELECTRICAL & ELECTRONICS (12) ────────────────────────────────────
    ("Solar Panels (380W Polycrystalline)", "electrical", 8500, "piece", 500,
     "Chennai, Tamil Nadu",
     "380W poly solar panels. 25-year performance warranty. IP67 junction box. Supplied to solar installers, rooftop project companies and agri-solar farms.",
     img("solar,panel,energy", 131)),
    ("3-Phase Electric Motors (1HP-10HP)", "electrical", 4800, "piece", 200,
     "Coimbatore, Tamil Nadu",
     "IE2 and IE3 efficiency class motors. IP55 protection. Used in pumps, compressors and machinery. BIS-certified. 1-year warranty.",
     img("motor,electric,industrial", 132)),
    ("MCB Circuit Breakers (Bulk)", "electrical", 85, "piece", 5000,
     "Noida, Uttar Pradesh",
     "6A to 63A MCBs. Type B and Type C available. IEC 60898 certified. Single-pole and double-pole models. Supplied to electrical contractors.",
     img("mcb,breaker,electrical", 133)),
    ("CCTV Cameras (4MP IP Dome)", "electrical", 1850, "piece", 1000,
     "Chennai, Tamil Nadu",
     "4MP IP dome cameras. H.265+ compression. 30m IR night vision. IP67 weatherproof. PoE powered. Supplied to security system integrators.",
     img("cctv,camera,security", 134)),
    ("Lithium Batteries (12V 100Ah)", "electrical", 12500, "piece", 200,
     "Bengaluru, Karnataka",
     "LFP lithium iron phosphate batteries. 2000+ cycle life. BMS protected. Used for solar storage and inverters. 3-year warranty.",
     img("battery,lithium,power", 135)),
    ("LED Street Lights (100W)", "electrical", 2800, "piece", 500,
     "Coimbatore, Tamil Nadu",
     "100W LED street lights. 140 lm/W efficacy. IP66 rated. 5-year warranty. Used by municipalities and industrial campuses. BEE registered.",
     img("led,streetlight,outdoor", 136)),
    ("Power Inverters (2KVA Hybrid)", "electrical", 6500, "piece", 300,
     "Chennai, Tamil Nadu",
     "2KVA hybrid solar inverter. Pure sine wave output. Grid-tie and off-grid modes. Battery and solar input. LCD display. 2-year warranty.",
     img("inverter,power,solar", 137)),
    ("LED Strip Lights (5M Roll)", "electrical", 320, "piece", 5000,
     "Surat, Gujarat",
     "SMD 5050 LED strip, 60 LEDs/metre. RGB and single colour. 12V DC. IP20 and IP65 variants. Used for decorative and commercial lighting.",
     img("led,strip,light", 138)),
    ("Copper Wiring (2.5 sq mm, 90m)", "electrical", 1850, "piece", 2000,
     "Chennai, Tamil Nadu",
     "FR grade PVC insulated copper wire. 2.5 sq mm conductor. IS:694 certified. Used for house wiring and panel wiring. Available in 90m coils.",
     img("wire,copper,electrical", 139)),
    ("Submersible Water Pumps (0.5HP)", "electrical", 3200, "piece", 500,
     "Coimbatore, Tamil Nadu",
     "0.5HP to 2HP borewell submersible pumps. Stainless steel body. 4-inch and 6-inch bore compatible. ISI-marked. 1-year warranty.",
     img("pump,submersible,water", 140)),
    ("UPS Systems (1KVA Online)", "electrical", 9800, "piece", 200,
     "Chennai, Tamil Nadu",
     "1KVA online UPS. Double conversion technology. Pure sine wave. 6ms transfer time. Rack and tower models. Supplied to offices and data centres.",
     img("ups,power,battery", 141)),
    ("Voltage Stabilizers (5KVA)", "electrical", 4500, "piece", 300,
     "Bengaluru, Karnataka",
     "5KVA servo voltage stabilizer. Input range 120V-280V. Digital display. Used for CNC machines, medical equipment and AC units. 2-year warranty.",
     img("stabilizer,voltage,electrical", 142)),

    # ── HANDICRAFTS & GIFTS (12) ──────────────────────────────────────────
    ("Tanjore Paintings (Traditional)", "handicrafts", 2500, "piece", 200,
     "Thanjavur, Tamil Nadu",
     "Traditional Tanjore paintings with gold foil work. Themes: deities, royalty and nature. Handmade by skilled artisans. Available in 12x18 to 24x36 inch sizes.",
     img("tanjore,painting,art", 146)),
    ("Brass Oil Lamps (Puja Diya)", "handicrafts", 450, "piece", 500,
     "Coimbatore, Tamil Nadu",
     "Handcrafted brass oil lamps. Traditional South Indian design. Height 12 to 24 inches. Suitable for temples, homes and gifting. Antique finish available.",
     img("brass,lamp,golden", 147)),
    ("Terracotta Pots & Pottery", "handicrafts", 180, "piece", 1000,
     "Vellore, Tamil Nadu",
     "Handmade terracotta pots, planters and decorative items. Natural clay, kiln-fired. Eco-friendly alternatives to plastic. Bulk pricing for garden stores.",
     img("terracotta,pottery,clay", 148)),
    ("Wooden Bobblehead Toys (Kondapalli)", "handicrafts", 380, "piece", 300,
     "Thanjavur, Tamil Nadu",
     "Traditional Thanjavur bobblehead (Thalayatti Bommai). Handpainted wooden toys. GI-tagged craft. Popular for gifts and home decor.",
     img("wooden,toy,craft", 149)),
    ("Bamboo Products (Baskets & Trays)", "handicrafts", 220, "piece", 800,
     "Nilgiris, Tamil Nadu",
     "Handwoven bamboo baskets, trays and organizers. Eco-friendly, sturdy. Made by tribal artisans. Supplied to home decor stores and exporters.",
     img("bamboo,basket,weave", 150)),
    ("Agarbatti (Scented Incense Sticks)", "handicrafts", 95, "box", 5000,
     "Bengaluru, Karnataka",
     "Premium scented agarbatti. Jasmine, rose, sandalwood and oudh fragrances. Charcoal-free, low smoke. Supplied to temples and spiritual goods stores.",
     img("incense,sticks,aromatic", 151)),
    ("Coconut Shell Crafts & Bowls", "handicrafts", 150, "piece", 500,
     "Kanyakumari, Tamil Nadu",
     "Eco-friendly coconut shell bowls, spoons and decorative items. Polished and lacquered finish. Supplied to eco stores and resort gift shops.",
     img("coconut,shell,craft", 152)),
    ("Handmade Scented Candles", "handicrafts", 280, "piece", 1000,
     "Chennai, Tamil Nadu",
     "Soy wax scented candles. 40+ fragrances. Burn time: 40-60 hours. Custom label printing available for gifting. Supplied to gift shops and hotels.",
     img("candle,handmade,wax", 153)),
    ("Kolam Rice Flour (White Powder)", "handicrafts", 60, "kg", 2000,
     "Madurai, Tamil Nadu",
     "Fine white rice flour for kolam (rangoli) art. Pure, free-flowing. Used in temples and homes. Packed in 1kg and 5kg bags.",
     img("kolam,powder,traditional", 154)),
    ("Granite Stone Idols (Custom)", "handicrafts", 8500, "piece", 50,
     "Mahabalipuram, Tamil Nadu",
     "Handcarved granite idols of deities. Traditional sculptors from Mahabalipuram. Custom sizes from 6 inch to 4 feet. Temple and home installation.",
     img("granite,idol,sculpture", 155)),
    ("Madhubani Artwork (Handpainted)", "handicrafts", 1200, "piece", 150,
     "Mithila, Bihar",
     "Authentic Madhubani paintings on handmade paper. Traditional Bihar folk art. Geometric and floral patterns. Supplied to galleries and gift exporters.",
     img("painting,folk,art", 156)),
    ("Batik Printed Silk Scarves", "handicrafts", 580, "piece", 300,
     "Jaipur, Rajasthan",
     "Hand batik-printed pure silk scarves. Traditional patterns. Natural dyes available. Supplied to boutiques and lifestyle gift stores.",
     img("batik,silk,scarf", 157)),

    # ── HEALTHCARE & PHARMA (12) ──────────────────────────────────────────
    ("Ayurvedic Herbal Hair Oil (Bulk)", "healthcare", 320, "litre", 500,
     "Coimbatore, Tamil Nadu",
     "Brahmi and bhringraj herbal hair oil. Cold-pressed coconut base. No mineral oil. Supplied to Ayurvedic brands, salons and wellness chains.",
     img("ayurveda,herbal,oil", 161)),
    ("Moringa Leaf Powder (Organic)", "healthcare", 380, "kg", 1000,
     "Salem, Tamil Nadu",
     "Certified organic moringa powder. 40+ nutrients. No additives. Spray-dried for maximum nutrition. Supplied to health food brands and nutraceutical companies.",
     img("moringa,powder,green", 162)),
    ("N95 Face Masks (CE Certified)", "healthcare", 35, "piece", 50000,
     "Ahmedabad, Gujarat",
     "CE and NIOSH-certified N95 respirators. 5-layer filtration. Adjustable nose clip. Used in hospitals, factories and construction sites.",
     img("mask,face,medical", 163)),
    ("Surgical Gloves (Latex – 100 pcs)", "healthcare", 280, "box", 2000,
     "Chennai, Tamil Nadu",
     "Examination-grade latex gloves. Powdered and powder-free. Sizes XS to XL. CE and FDA compliant. Supplied to hospitals and diagnostic centres.",
     img("gloves,surgical,medical", 164)),
    ("First Aid Kits (Industrial)", "healthcare", 1850, "piece", 500,
     "Bengaluru, Karnataka",
     "25-person industrial first aid kit. OSHA compliant. Contains bandages, antiseptics, burn gel, eye wash. Used in factories and construction sites.",
     img("firstaid,kit,medical", 165)),
    ("Neem Leaf Powder (Pure)", "healthcare", 185, "kg", 2000,
     "Coimbatore, Tamil Nadu",
     "Pure neem leaf powder. Air-dried and finely milled. Antibacterial properties. Used in herbal toothpaste, skincare and Ayurvedic formulations.",
     img("neem,herb,green", 166)),
    ("Ashwagandha Root Extract (5%)", "healthcare", 2800, "kg", 200,
     "Coimbatore, Tamil Nadu",
     "Standardised ashwagandha extract, 5% withanolides. Water-soluble. Used in health supplements and nutraceuticals. COA provided for every batch.",
     img("herb,ashwagandha,supplement", 167)),
    ("Aloe Vera Gel (Cold Processed)", "healthcare", 120, "litre", 2000,
     "Rajkot, Gujarat",
     "99% pure aloe vera inner leaf gel. Cold processed. Used in skincare, hair care and food supplements. COSMOS certified. Supplied in bulk.",
     img("aloe,vera,green", 168)),
    ("Turmeric Extract Capsules (Bulk)", "healthcare", 480, "kg", 500,
     "Chennai, Tamil Nadu",
     "Curcumin 95% turmeric extract capsules. Piperine added for bioavailability. GMP-certified facility. Supplied to nutraceutical brands.",
     img("turmeric,capsule,supplement", 169)),
    ("Disposable Syringes (3ml – 100 pcs)", "healthcare", 85, "box", 5000,
     "Chennai, Tamil Nadu",
     "3ml luer slip disposable syringes. ISO 13485 certified. Sterile and individually blister packed. Supplied to hospitals, clinics and diagnostic centres.",
     img("syringe,medical,disposable", 170)),
    ("Immunity Booster Herbal Tea", "healthcare", 380, "kg", 1000,
     "Coimbatore, Tamil Nadu",
     "Tulsi, ginger, pepper and cinnamon herbal tea blend. No artificial flavours. FSSAI certified. Supplied to health stores and online nutrition brands.",
     img("herbal,tea,health", 171)),
    ("Triphala Churna (Bulk)", "healthcare", 220, "kg", 1500,
     "Coimbatore, Tamil Nadu",
     "Classic Ayurvedic Triphala churna. Equal parts amla, haritaki and bibhitaki. GMP-certified manufacturing. Supplied to Ayurvedic pharmacies and brands.",
     img("ayurveda,herbs,powder", 172)),

    # ── PLASTICS & PACKAGING (12) ─────────────────────────────────────────
    ("HDPE Carry Bags (Customised)", "plastics", 12, "kg", 10000,
     "Chennai, Tamil Nadu",
     "HDPE carry bags. 30 to 100 micron. Custom printing up to 4 colours. Available in all sizes. Supplied to supermarkets and garment retailers.",
     img("plastic,bag,hdpe", 176)),
    ("PET Bottles (500ml – Clear)", "plastics", 8, "piece", 100000,
     "Ahmedabad, Gujarat",
     "Clear PET bottles, 500ml with cap. Food-grade. BPA-free. Used for water, juices and sauces. Custom moulding available for bulk orders.",
     img("bottle,plastic,pet", 177)),
    ("PP Woven Sacks (50kg capacity)", "plastics", 18, "piece", 50000,
     "Ahmedabad, Gujarat",
     "Polypropylene woven sacks. 50 kg capacity. Laminated and unlaminated options. Custom printing available. Used for cement, rice and feed packing.",
     img("sack,woven,packaging", 178)),
    ("Corrugated Cardboard Boxes (5-ply)", "plastics", 45, "piece", 20000,
     "Chennai, Tamil Nadu",
     "5-ply corrugated shipping boxes. Sizes from A4 to 24x18x18 inch. Custom printing available. Supplied to e-commerce, food and garment industries.",
     img("box,corrugated,cardboard", 179)),
    ("Bubble Wrap (50m Roll)", "plastics", 380, "piece", 2000,
     "Coimbatore, Tamil Nadu",
     "10mm bubble wrap, 1.2m width, 50m length. Anti-static and standard grades. Used for fragile product packaging. Supplied to logistics companies.",
     img("bubble,wrap,packaging", 180)),
    ("Shrink Wrap Film (Industrial)", "plastics", 2800, "piece", 500,
     "Ahmedabad, Gujarat",
     "POF shrink wrap film, 19 micron. 400mm and 500mm width. Used on shrink tunnels for retail packaging. Supplied in 3kg rolls.",
     img("shrink,wrap,film", 181)),
    ("Food-Grade PP Containers (1L)", "plastics", 22, "piece", 50000,
     "Chennai, Tamil Nadu",
     "Microwaveable PP containers with airtight lids. 1L capacity. BPA-free, food-safe. Supplied to meal kit companies, dairies and caterers.",
     img("container,food,plastic", 182)),
    ("Paper Cups (250ml – 1000 pcs)", "plastics", 380, "piece", 5000,
     "Coimbatore, Tamil Nadu",
     "Single-wall paper cups, 250ml. PE-lined, leak-proof. Custom printing available. Used in offices, events and food courts. MOQ: 5000 pcs.",
     img("paper,cup,disposable", 183)),
    ("Thermoform Trays (Black PS)", "plastics", 5, "piece", 100000,
     "Chennai, Tamil Nadu",
     "Black polystyrene thermoform trays. Various compartment sizes. Used for meat, seafood and fresh produce display. Food-grade, recyclable.",
     img("tray,plastic,packaging", 184)),
    ("Ziplock Bags (Food Grade, 100 pcs)", "plastics", 85, "piece", 10000,
     "Surat, Gujarat",
     "LDPE ziplock resealable bags. Food-grade, BPA-free. Sizes from 3x4 inch to 12x15 inch. Used for spices, snacks and pharmaceutical packaging.",
     img("ziplock,bag,seal", 185)),
    ("Multi-Layer Flexible Pouches", "plastics", 3200, "kg", 500,
     "Ahmedabad, Gujarat",
     "3-layer and 5-layer flexible pouches for snacks, masala and dairy. Reverse-printed. High barrier. Supplied to FMCG brands and co-packers.",
     img("pouch,packaging,flexible", 186)),
    ("HDPE Drum (200L Industrial)", "plastics", 1850, "piece", 1000,
     "Chennai, Tamil Nadu",
     "200-litre HDPE drums with tight-head and open-head options. UN-certified. Used for chemical, food and pharma storage and transport.",
     img("drum,hdpe,barrel", 187)),
]

SELLER_PHONE = "9999999999"
SELLER_NAME = "SourceDirect Demo Store"

def main():
    conn = sqlite3.connect(DB)
    cur = conn.cursor()

    for stmt in SCHEMA.strip().split(";"):
        s = stmt.strip()
        if s:
            cur.execute(s)
    conn.commit()

    cur.execute(
        "INSERT OR IGNORE INTO users (phone, role, name) VALUES (?, 'seller', ?)",
        (SELLER_PHONE, SELLER_NAME),
    )
    conn.commit()
    cur.execute("SELECT id FROM users WHERE phone = ?", (SELLER_PHONE,))
    seller_id = cur.fetchone()[0]

    inserted = 0
    for title, category, price, unit, qty, location, desc, img_url in PRODUCTS:
        cur.execute(
            """INSERT INTO listings
               (seller_id, title, description, category, price, unit,
                quantity, location_name, media_urls_json)
               VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)""",
            (seller_id, title, desc, category, price, unit,
             qty, location, json.dumps([img_url])),
        )
        inserted += 1

    conn.commit()

    # Mark demo seller as verified
    cur.execute(
        "UPDATE users SET subscription_status = 'verified' WHERE phone = ?",
        (SELLER_PHONE,),
    )
    conn.commit()
    conn.close()
    print(f"Seeded {inserted} listings for seller {SELLER_PHONE} (verified)")


if __name__ == "__main__":
    main()
